Badaro/MTGOFormatData

Formats/Pioneer/Archetypes/Angels.json, Formats/Pioneer/Archetypes/DevotionWalkers.json, Formats/Pioneer/Archetypes/GlittersStompy.json, Formats/Pioneer/Archetypes/Gyruda.json, Formats/Pioneer/Archetypes/Humans.json, Formats/Pioneer/Archetypes/Lutri.json, Formats/Pioneer/Archetypes/Phoenix.json, Formats/Pioneer/Archetypes/Pyromancer.json, Formats/Pioneer/Archetypes/Rally.json, Formats/Pioneer/Archetypes/StarfieldControl.json, Formats/Pioneer/Archetypes/Vehicles.json
* Added Angels, Lutri Control, Vehicles and Glitters Stompy
* Removed unused parameters from "InMainboard" conditions, only the first one was used
=> Pioneer improvements

Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/Archetypes/Mono Black.json, Formats/Legacy/Archetypes/Tempo.json, Formats/Legacy/Archetypes/Vial.json, Formats/Legacy/Archetypes/vial.json, Formats/Modern/Archetypes/Elementals.json, Formats/Modern/Archetypes/Insects.json, Formats/Modern/Archetypes/OmnathControl.json, Formats/Modern/Archetypes/RedAggro.json, Formats/Modern/Archetypes/Titan.json, Formats/Modern/Archetypes/UnderworldBreachCombo.json
A bunch of changes required in Modern, specifically changes for the new URx Breach value piles. 
Tried the compare option to make sure that everything works.
=> Fr changes

Formats/Legacy/Archetypes/MonoB_Depths.json, Formats/Pioneer/Fallbacks/Midrange.json
Still requires a bunch of other changes in Legacy to come this week by Lardach
=> QuickFix Pioneer and Leg

Formats/Legacy/Archetypes/Cephalid painter.json, Formats/Legacy/Archetypes/Control.json, Formats/Legacy/Archetypes/Mono Black.json, Formats/Legacy/Archetypes/Painter.json, Formats/Legacy/Archetypes/Tempo.json
New PR with fixed conflicts from #10
=> change 02-28-2023

Formats/Legacy/Archetypes/Canadian Threshold.json
Update Canadian Threshold.json
=> Change 03-28-2023

Formats/Legacy/Archetypes/8-cast.json, Formats/Legacy/Archetypes/Blink.json, Formats/Legacy/Archetypes/Jund.json, Formats/Legacy/Archetypes/Lands.json, Formats/Pioneer/Archetypes/Creativity.json, Formats/Pioneer/Archetypes/UW Ctrl.json
=> Change 06-19-2023

Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/metas.json, Formats/Pioneer/Archetypes/ArtifactAggro.json, Formats/Pioneer/Archetypes/GodPharaohGift.json, Formats/Pioneer/Fallbacks/Aggro.json, Formats/Pioneer/Fallbacks/Control.json
=> Change 06-26-2023

Formats/Legacy/Archetypes/D&T.json, Formats/Legacy/Archetypes/Deadly brew.json, Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/Archetypes/Depths.json, Formats/Legacy/Archetypes/Dungeon.json, Formats/Legacy/Archetypes/Maverick.json, Formats/Legacy/Archetypes/Mono Black.json, Formats/Legacy/Archetypes/Samwise.json, Formats/Legacy/Archetypes/Stoneblade.json, Formats/Legacy/Archetypes/Vial.json, Formats/Legacy/Archetypes/vial.json, Formats/Pioneer/Archetypes/ArtifactAggro.json
=> Change 07-24-2023

Formats/Legacy/Archetypes/Control.json, Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/Archetypes/Mystic Forge combo.json, Formats/Legacy/Archetypes/Reanimator.json, Formats/Legacy/Archetypes/TES.json
=> Change 09-11-2023

Formats/Legacy/Archetypes/Control.json, Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/Archetypes/Goblins.json, Formats/Legacy/Archetypes/Sticker Goblin.json, Formats/Pauper/Archetypes/control.json
Legacy & Pauper
Pioneer no change.
=> Change 10-03-2023

Formats/Pauper/Archetypes/Mono B control.json, Formats/Pauper/Archetypes/White_Aggro.json, Formats/Pauper/Archetypes/control.json, Formats/Pioneer/Archetypes/Ascendancy.json, Formats/Pioneer/Archetypes/Spirits.json
Pauper & Pionner
Legacy next week
=> Change 10-10-2023

Formats/Legacy/Archetypes/8-cast.json, Formats/Legacy/Archetypes/Control.json, Formats/Legacy/Archetypes/Delver.json, Formats/Legacy/Archetypes/Mind's Desire.json, Formats/Legacy/Archetypes/Scales.json, Formats/Pauper/Archetypes/Initiative.json, Formats/Pioneer/Archetypes/AzoriusControl.json, Formats/Pioneer/Archetypes/Zur enigmatic.json
Pioneer & Pauper.
Legacy work in progress.
=> Change 10-17-2023

Formats/Pauper/Archetypes/Burn.json, Formats/Pauper/Archetypes/Faeries.json, Formats/Pauper/Archetypes/Garden control.json, Formats/Pauper/Archetypes/Mono B control.json, Formats/Pauper/Archetypes/Mono G Aggro.json, Formats/Pauper/Archetypes/Mono U aggro.json
Pauper : Change
Pioneer : No change
Legacy : No Work
=> Change 10-24-2023

Formats/Pioneer/Archetypes/ArtifactAggro.json, Formats/Pioneer/Archetypes/Knight.json
=> Change 11-14-2023

Formats/Legacy/metas.json, Formats/Pauper/Archetypes/BG Midrange.json, Formats/Pauper/Archetypes/Burn.json, Formats/Pauper/Archetypes/Goblins.json, Formats/Pauper/Archetypes/control.json, Formats/Pauper/metas.json, Formats/Pioneer/Archetypes/Amalia combo.json, Formats/Pioneer/Archetypes/Toxic.json, Formats/Pioneer/Archetypes/Trumpeting combo.json, Formats/Pioneer/metas.json
=> Change 11-20-2023

Formats/Pauper/Archetypes/control.json, Formats/Pioneer/Archetypes/Cycling.json, Formats/Pioneer/Archetypes/Dinosaur.json, Formats/Pioneer/Archetypes/Discover combo.json, Formats/Pioneer/Archetypes/LotusStrings.json, Formats/Pioneer/Archetypes/MonoBlueDevotion.json, Formats/Pioneer/Archetypes/Rally.json, Formats/Pioneer/Archetypes/Vehicule.json
=> Change 11-29-2023

Formats/Pauper/Archetypes/Burn.json, Formats/Pauper/Archetypes/Initiative.json, Formats/Pauper/Archetypes/Kuldotha.json, Formats/Pauper/metas.json, Formats/Pioneer/Archetypes/Madness.json, Formats/Pioneer/metas.json
=> Change to 12-11-2023

Formats/Legacy/Archetypes/Burn.json, Formats/Legacy/Archetypes/Storm.json, Formats/Pauper/Archetypes/graveyard.json, Formats/Pioneer/Archetypes/BringToLight.json, Formats/Pioneer/Archetypes/LotusStrings.json
=> Change to 12-28-2023

Formats/Legacy/Archetypes/Hogaak.json, Formats/Legacy/Archetypes/Midrange.json, Formats/Legacy/Archetypes/Monolith combo.json, Formats/Legacy/Archetypes/hogaak.json
=> Change 01-02-2024

Formats/Standard/Archetypes/5cMidrange.json, Formats/Standard/Archetypes/Artifacts.json, Formats/Standard/Archetypes/BGxMidrange.json, Formats/Standard/Archetypes/BxMidrange.json, Formats/Standard/Archetypes/Cascade.json, Formats/Standard/Archetypes/Control.json, Formats/Standard/Archetypes/Domain.json, Formats/Standard/Archetypes/Enchantments.json, Formats/Standard/Archetypes/EsperLegends.json, Formats/Standard/Archetypes/EsperMidrange.json, Formats/Standard/Archetypes/GxMidrange.json, Formats/Standard/Archetypes/Humans.json, Formats/Standard/Archetypes/Poison.json, Formats/Standard/Archetypes/Reanimator.json, Formats/Standard/Archetypes/RonaCombo.json, Formats/Standard/Archetypes/RxAggro.json, Formats/Standard/Archetypes/Soldiers.json, Formats/Standard/Archetypes/UBxTempo.json, Formats/Standard/Archetypes/UxMidrange.json, Formats/Standard/Archetypes/UxTempo.json, Formats/Standard/Archetypes/WxAggro.json, Formats/Standard/Archetypes/WxMidrange.json, Formats/Standard/Fallbacks/Aggro.json, Formats/Standard/Fallbacks/Control.json, Formats/Standard/Fallbacks/Midrange.json, Formats/Standard/Fallbacks/Ramp.json, Formats/Standard/Fallbacks/Reanimator.json, Formats/Standard/color_overrides.json, Formats/Standard/metas.json, README.md
=> New Format: Standard

Formats/Vintage/Archetypes/Aggro Shops.json
=> Update Aggro Shops.json

Formats/Legacy/Archetypes/Arclight phoenix.json, Formats/Legacy/Archetypes/Lands.json, Formats/Legacy/Archetypes/Patchwork Stompy.json, Formats/Pioneer/Archetypes/Vampire.json
=> Change to 02-26-2024

Formats/Modern/Archetypes/Scam.json
They are splashing green for pick your poison. But it's the same deck.
=> [Modern] Scam update

Formats/Legacy/Archetypes/8-cast.json, Formats/Legacy/Archetypes/Scam.json, Formats/Legacy/Archetypes/Vial.json, Formats/Pioneer/Archetypes/LotusStrings.json, Formats/Standard/Archetypes/RUGControl.json
Minors in Pioneer, Legacy and standard
=> Post PT Thunder update

Formats/Legacy/Archetypes/Bant Toollbox.json, Formats/Legacy/Archetypes/Blink.json, Formats/Legacy/Archetypes/Depths.json, Formats/Legacy/Archetypes/Hammer.json, Formats/Legacy/Archetypes/Human.json, Formats/Legacy/Archetypes/Initiative.json, Formats/Legacy/Archetypes/Lands.json, Formats/Legacy/Archetypes/Madness.json, Formats/Legacy/Archetypes/Mentor.json, Formats/Legacy/Archetypes/Misfortune.json, Formats/Legacy/Archetypes/Mystic Forge combo.json, Formats/Legacy/Archetypes/Reanimator.json, Formats/Legacy/Archetypes/Sliver.json, Formats/Legacy/Archetypes/Thought Lash combo.json, Formats/Legacy/Archetypes/helm yorion.json, Formats/Pauper/Archetypes/Mono B control.json, Formats/Pauper/Archetypes/Tireless Tribe.json, Formats/Pioneer/Archetypes/Auras.json, Formats/Pioneer/Archetypes/Lutri.json
standardize all condition type capitalization as title case and capitalize all condition keys
=> standardize all condition type capitalization as title case

Formats/Vintage/Archetypes/AggroVine.json, Formats/Vintage/Archetypes/Blue Ring.json, Formats/Vintage/Archetypes/Breach.json, Formats/Vintage/Archetypes/Esper Saga.json, Formats/Vintage/Archetypes/Jeskai.json, Formats/Vintage/Archetypes/Sphere Shops.json, Formats/Vintage/Fallbacks/Other Aggro.json, Formats/Vintage/Fallbacks/Other Blue Tempo.json, Formats/Vintage/Fallbacks/Other Combo.json, Formats/Vintage/Fallbacks/Other Tinker.json, Formats/Vintage/Fallbacks/Other.json
Solving https://github.com/Badaro/MTGOFormatData/issues/111
Not squashing this PR so that future updates from @IamActuallyLvL1 won't cause conflicts.
=> [Vintage] Merging IamActuallyLvL1 Vintage updates
